<table border="1"><tbody>
	    <tr><td colspan="4" align="center"><h1>Claro S.A.</h1></td></tr>
	    <tr><td colspan="4"><strong>Factura #6</strong></td></tr>
	    <tr><td colspan="4"><strong>Nit: 22413641-4</strong></td></tr>
	    <tr><td colspan="4"><strong>Direccion: Cra 42h # 84 - 101</strong></td></tr>
	    <tr><td colspan="4">&nbsp;</td></tr>
	    <tr><td>Nombre:</td><td colspan="3">Yaledys Machacon Garces</td></tr>
	    <tr><td>Fecha:</td><td colspan="3">2012-11-09 18:48:47</td></tr>
	    <tr><td>Fecha ven:</td><td colspan="3">2012-12-09</td></tr>
	    <tr><td>Email:</td><td colspan="3">yaledyspaola@gmail.com</td></tr>
	    <tr><td>Direccion:</td><td colspan="3">calle 74 - 1 # 70 - 14 - 2</td></tr>
	    <tr><td>Ubicacion:</td><td colspan="3">1</td></tr>
	    <tr><td colspan="4">&nbsp;</td></tr>
	    <tr><td colspan="4"><strong>Detalle de la compra</strong></td></tr>
	    <tr><td><strong>Paquete</strong></td><td><strong>Servicio</strong></td><td><strong>Descripcion del Servicio</strong></td><td><strong>Precio del servicio</strong></td></tr><tr><td rowspan="3">Personal</td><td>telefonia movil (prepago)</td><td>40 min</td><td align="right">$15000</td></tr><tr><td>internet movil (prepago)</td><td>1MB</td><td align="right">$150000</td></tr><tr><td colspan="2"><strong>Subtotal</strong></td><td align="right"><strong>$40000</strong></td></tr><tr><td rowspan="4">Basico</td><td>telefonia movil (prepago)</td><td>40 min</td><td align="right">$15000</td></tr><tr><td>internet movil (prepago)</td><td>1MB</td><td align="right">$150000</td></tr><tr><td>television (personal)</td><td>digital</td><td align="right">$60000</td></tr><tr><td colspan="2"><strong>Subtotal</strong></td><td align="right"><strong>$80000</strong></td></tr><tr><td rowspan="5">Empresarial</td><td>telefonia movil (postpago) 2</td><td>120 min</td><td align="right">$90000</td></tr><tr><td>internet banda ancha (empresarial) 2</td><td>2 GB</td><td align="right">$450000</td></tr><tr><td>television (personal) 2</td><td>digital avanzada</td><td align="right">$95000</td></tr><tr><td>telefonia fija (empresarial) 2</td><td>900 min</td><td align="right">$180000</td></tr><tr><td colspan="2"><strong>Subtotal</strong></td><td align="right"><strong>$180000</strong></td></tr><tr><td rowspan="6">Xtreme</td><td>telefonia movil (postpago) 3</td><td>180 min</td><td align="right">$135000</td></tr><tr><td>internet movil (postpago) 2</td><td>2 MB</td><td align="right">$80000</td></tr><tr><td>internet banda ancha (empresarial) 3</td><td>4 GB</td><td align="right">$800000</td></tr><tr><td>telefonia fija (empresarial) 3</td><td>ilimitado</td><td align="right">$220000</td></tr><tr><td>television (personal) 3</td><td>Full HD</td><td align="right">$130000</td></tr><tr><td colspan="2"><strong>Subtotal</strong></td><td align="right"><strong>$220000</strong></td></tr><tr><td rowspan="6">Xtreme</td><td>telefonia movil (postpago) 3</td><td>180 min</td><td align="right">$135000</td></tr><tr><td>internet movil (postpago) 2</td><td>2 MB</td><td align="right">$80000</td></tr><tr><td>internet banda ancha (empresarial) 3</td><td>4 GB</td><td align="right">$800000</td></tr><tr><td>telefonia fija (empresarial) 3</td><td>ilimitado</td><td align="right">$220000</td></tr><tr><td>television (personal) 3</td><td>Full HD</td><td align="right">$130000</td></tr><tr><td colspan="2"><strong>Subtotal</strong></td><td align="right"><strong>$220000</strong></td></tr><tr><td colspan="4">&nbsp;</td></tr>
	    <tr><td colspan="3"><b>Total:</b></td><td align="right"><b>$740000</b></td></tr>
	    </tbody></table>
